// <auto-generated />
namespace KidKinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class created_gallery_table_and_booaseat_classroom_connection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(created_gallery_table_and_booaseat_classroom_connection));
        
        string IMigrationMetadata.Id
        {
            get { return "202402290902273_created_gallery_table_and_booaseat_classroom_connection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
