// <auto-generated />
namespace KidKinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class created_adress_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(created_adress_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202402131211390_created_adress_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
